# Generated by Django 5.0.2 on 2024-02-23 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_bookauthor_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isbn',
            new_name='ISBN',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='cover',
            new_name='cover_image',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='page',
            new_name='page_count',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='published',
            new_name='published_date',
        ),
    ]
